<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/LICENSE
 */

?>
<form id="wirecard_elasticengine_credit_card_three_d_form"
      method="<?= $block->escapeHtml($block->getMethod()) ?>" action="<?= $block->escapeHtml($block->getAction()) ?>">
    <?php foreach ($block->getFormFields() as $name => $value): ?>
        <input type="hidden" name="<?= $block->escapeHtml($name) ?>" value="<?= $block->escapeHtml($value) ?>" />
    <?php endforeach; ?>
</form>
