<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/LICENSE
 */

if ($this->isPia()) {

    $merchantAccount = $this->getMerchantBankAccount();
    ?>

    <br>


    <table style="width:auto;">
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td colspan="2"><b><?php echo __('transfer_notice') ?></b></td>
        </tr>
        <tr>
            <td><?php echo __('amount') ?></td>
            <td><?php echo $this->getAmount() ?></td>
        </tr>
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td><?php echo __('iban') ?></td>
            <td><?php echo $merchantAccount['iban'] ?></td>
        </tr>
        <tr>
            <td><?php echo __('bic') ?></td>
            <td><?php echo $merchantAccount['bic'] ?></td>
        </tr>
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td><?php echo __('ptrid') ?></td>
            <td><?php echo $this->getPtrid() ?></td>
        </tr>
    </table>
    <br>

<?php } ?>