<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/LICENSE
 */

if ($block->isPia()) {

    $merchantAccount = $block->getMerchantBankAccount();
    ?>

    <br>


    <table style="width:auto;">
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td colspan="2"><b><?= $block->escapeHtml(__('transfer_notice')) ?></b></td>
        </tr>
        <tr>
            <td><?= $block->escapeHtml(__('amount')) ?></td>
            <td><?= $block->escapeHtml($block->getAmount()) ?></td>
        </tr>
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td><?= $block->escapeHtml(__('iban')) ?></td>
            <td><?= $block->escapeHtml($merchantAccount['iban']) ?></td>
        </tr>
        <tr>
            <td><?= $block->escapeHtml(__('bic')) ?></td>
            <td><?= $block->escapeHtml($merchantAccount['bic']) ?></td>
        </tr>
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td><?= $block->escapeHtml(__('ptrid')) ?></td>
            <td><?= $block->escapeHtml($block->getPtrid()) ?></td>
        </tr>
    </table>
    <br>

<?php } ?>