<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard AG and are explicitly not part
 * of the Wirecard AG range of products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 3 (GPLv3) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard AG does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard AG does not guarantee their full
 * functionality neither does Wirecard AG assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard AG does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */

if ($this->isPia()) {

    $merchantAccount = $this->getMerchantBankAccount();
    ?>

    <br>


    <table border="0" cellpadding="0" cellspacing="0" style="width:auto;">
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td colspan="2"><b><?php echo __('Please transfer the amount using the following data:') ?></b></td>
        </tr>
        <tr>
            <td><?php echo __('Amount') ?></td>
            <td><?php echo $this->getAmount() ?></td>
        </tr>
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td>IBAN</td>
            <td><?php echo $merchantAccount['iban'] ?></td>
        </tr>
        <tr>
            <td>BIC</td>
            <td><?php echo $merchantAccount['bic'] ?></td>
        </tr>
        <tr style="background-color: rgba(0,0,0,0.1)">
            <td><?php echo __('Provider transaction reference id') ?></td>
            <td><?php echo $this->getPtrid() ?></td>
        </tr>
    </table>
    <br>

<?php } ?>