<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/LICENSE
 */

$mandateId = $block->getMandateId();
?>
<table  class="stretch">
    <tr>
        <td class="text11justify">
            <table>
                <tr>
                    <td class="text11justify">
                        <i ><?= $block->escapeHtml(__('creditor')) ?></i><br />
                        <?= $block->escapeHtml($block->getCreditorName()) ?>,
                        <?= $block->escapeHtml($block->getStoreCity()) ?><br />
                        <?= $block->escapeHtml(__('config_creditor_id')) ?>
                        <?= $block->escapeHtml($block->getCreditorId()) ?><br />
                        <?= $block->escapeHtml(__('creditor_mandate_id')) ?>
                        <?= $block->escapeHtml($mandateId) ?><br />
                        <input type="hidden" name="mandateId" value="<?= $block->escapeHtml($mandateId) ?>">
                    </td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table>
                <tr>
                    <td class="text11">
                        <i><?= $block->escapeHtml(__('debtor')) ?></i><br />
                        <?= $block->escapeHtml(__('debtor_acc_owner')) ?> %firstname% %lastname%<br />
                        <?= $block->escapeHtml(__('iban')) ?> %bankAccountIban% <br />
                        <?php if ($block->getBankBicEnabled()) {
                            echo $block->escapeHtml(__('bic')) ?> %bankBic% <br /><?php
                        }
                        ?>
                    </td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="text11justify">
            <table>
                <tr>
                    <td class="text11justify">
                        <?= $block->escapeHtml(__('sepa_text_1') . ' ' .
                            $block->getCreditorName() . ' ' .
                            __('sepa_text_2') . ' ' .
                            $block->getCreditorName() .
                            __('sepa_text_2b')); ?>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="text11justify">
                        <?= $block->escapeHtml(__('sepa_text_3')) ?>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="text11justify">
                        <?= $block->escapeHtml(__('sepa_text_4') . ' ' .
                            $block->getCreditorName() . ' ' .
                                    __('sepa_text_5')); ?>
                    </td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="text11justify">
            <table>
                <tr>
                    <td class="text11justify">
                        <?= $block->escapeHtml($block->getStoreCity()) ?>,
                        <?= $block->escapeHtml(date("d.m.Y")) ?> %firstname% %lastname%
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <input type="checkbox" id="sepa-accept"><label for="sepa-accept">
                            <?= $block->escapeHtml(__('sepa_text_6')) ?><label
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>