
<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard AG and are explicitly not part
 * of the Wirecard AG range of products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 3 (GPLv3) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard AG does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard AG does not guarantee their full
 * functionality neither does Wirecard AG assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard AG does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */

$mandateId = $this->getMandateId();
?>
<table border="0" cellpadding="0" cellspacing="0" class="stretch">
    <tr>
        <td class="text11justify">
            <table border="0" width="100%">
                <tr>
                    <td class="text11justify">
                        <i ><?php echo __('creditor') ?></i><br />
                        <?php echo $this->getCreditorName() ?>, <?php echo $this->getStoreCity() ?><br />
                        <?php echo __('config_creditor_id') ?> <?php echo $this->getCreditorId() ?><br />
                        <?php echo __('creditor_mandate_id') ?> <?php echo $mandateId ?><br />
                        <input type="hidden" name="mandateId" value="<?php echo $mandateId ?>">
                    </td>
                    <td width="10%">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table border="0" width="100%">
                <tr>
                    <td class="text11">
                        <i><?php echo __('debtor') ?></i><br />
                        <?php echo __('debtor_acc_owner') ?> %firstname% %lastname%<br />
                        <?php echo __('iban') ?> %bankAccountIban% <br />
                        <?php if($this->getBankBicEnabled()) {
                            echo __('bic') ?> %bankBic% <br /><?php
                                }
                                ?>
                    </td>
                    <td width="10%">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="text11justify">
            <table border="0" width="100%">
                <tr>
                    <td class="text11justify">
                        <?php echo __('sepa_text_1') . ' ' .
                            $this->getCreditorName() . ' ' .
                            __('sepa_text_2') . ' ' .
                            $this->getCreditorName() .
                            __('sepa_text_2b'); ?>
                    </td>
                    <td width="10%">&nbsp;</td>
                </tr>
                <tr>
                    <td class="text11justify">
                        <?php echo __('sepa_text_3') ?>
                    </td>
                    <td width="10%">&nbsp;</td>
                </tr>
                <tr>
                    <td class="text11justify">
                        <?php echo __('sepa_text_4') . ' ' .
                                    $this->getCreditorName() . ' ' .
                                    __('sepa_text_5'); ?>
                    </td>
                    <td width="10%">&nbsp;</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="text11justify">
            <table border="0" width="100%">
                <tr>
                    <td class="text11justify">
                        <?php echo $this->getStoreCity() ?>, <?php echo date("d.m.Y") ?> %firstname% %lastname%
                    </td>
                    <td width="10%">&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <input type="checkbox" id="sepa-accept"><label for="sepa-accept"><?php echo __('sepa_text_6') ?><label
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>