<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/LICENSE
 */

/**
 * @var $block \Wirecard\ElasticEngine\Block\Adminhtml\System\Config\TestCredentials
 */
?>
<script type="application/javascript">
    require(["jquery", "Magento_Ui/js/modal/alert"], function ($, alert) {
        function testCredentials(sectionName) {
            let baseUrl = document.getElementById(sectionName + "_base_url");
            let httpUser = document.getElementById(sectionName + "_http_user");
            let httpPassword = document.getElementById(sectionName + "_http_pass");

            new Ajax.Request("<?= $block->escapeHtml($block->getAjaxUrl()) ?>", {
                parameters: {
                    baseUrl: baseUrl.value,
                    httpUser: httpUser.value,
                    httpPass: httpPassword.value
                },
                loaderArea: false,
                asynchronous: true,
                onError: onErrorHandler,
                onSuccess: onSuccessHandler
            });
        }

        function alertResult(message) {
            alert({
                title: "<?= $block->escapeHtml(__('test_credentials')) ?>",
                content: message,
                actions: {
                    always: function () {
                    }
                }
            });
        }

        function onErrorHandler() {
            let message = "<?= $block->escapeHtml(__('error_credentials')) ?>";
            alertResult(message);
        }

        function onSuccessHandler(response) {
            if (response.responseJSON.valid) {
                alertResult(response.responseJSON.message);
            } else {
                alertResult(response.responseJSON.message);
            }
        }

        window.testCredentials = testCredentials;
    });
</script>
<button onclick="javascript:testCredentials('<?= $block->escapeHtml($block->getDataByKey('section_name')) ?>'); return false;"
        class="submit btn" type="button" id="<?= $block->escapeHtml($block->escapeHtmlAttr($block->getHtmlId())) ?>">
    <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>
