<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/LICENSE
 */

/**
 * @var $block \Wirecard\ElasticEngine\Block\Adminhtml\System\Config\TestCredentials
 */
?>
<script type="application/javascript">
    require(['jquery', 'Magento_Ui/js/modal/alert'], function ($, alert) {
        function testCredentials(sectionName) {
            let baseUrl = document.getElementById(sectionName + '_base_url');
            let httpUser = document.getElementById(sectionName + '_http_user');
            let httpPassword = document.getElementById(sectionName + '_http_pass');

            new Ajax.Request('<?= $block->getAjaxUrl() ?>', {
                parameters: {
                    baseUrl: baseUrl.value,
                    httpUser: httpUser.value,
                    httpPass: httpPassword.value
                },
                loaderArea: false,
                asynchronous: true,
                onSuccess: onSuccessHandler
            });
        }

        function alertResult(message) {
            alert({
                title: $.mage.__('test_credentials'),
                content: $.mage.__(message),
                actions: {
                    always: function () {
                    }
                }
            });
        }

        function onSuccessHandler(response) {
            if (response.responseJSON.valid) {
                alertResult(response.responseJSON.message);
            } else {
                alertResult(response.responseJSON.message);
            }
        }

        window.testCredentials = testCredentials;
    });
</script>
<button onclick="javascript:testCredentials('<?= $block->getDataByKey('section_name') ?>'); return false;"
        class="submit btn" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
    <span><?= $block->getButtonLabel() ?></span>
</button>
