<?php
/**
 * @var $block \Wirecard\ElasticEngine\Block\Widget\TestCredentialsButton
 */

echo $block->getButtonHtml();
?>
<script type="application/javascript">
    require([
        'jquery'
    ], function($){
        $('#button_test_credentials').click(function() {
            new Ajax.Request('<?= $block->getAjaxUrl() ?>', {
                parameters:   {
                    baseUrl: $('#wirecard_elasticengine_credentials_base_url').val(),
                    httpUser: $('#wirecard_elasticengine_credentials_http_user').val(),
                    httpPass: $('#wirecard_elasticengine_credentials_http_pass').val()
                },
                loaderArea:   false,
                asynchronous: true,
                onSuccess: function(response) {
                    console.log(response);
                }
            });
        })
    });
</script>
