<?php
/**
 * @var $block \Wirecard\ElasticEngine\Block\Widget\TestCredentialsButton
 */

echo $block->getButtonHtml();
?>
<script type="application/javascript">
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        jQuery('#button_test_credentials').click(function() {
            new Ajax.Request('<?= $block->getAjaxUrl() ?>', {
                parameters:   {},
                loaderArea:   false,
                asynchronous: true,
                onSuccess: function(response) {
                    console.log(response);
                }
            });
        })
    });
</script>
