<?php
/**
 * Shop System Plugins - Terms of Use
 *
 * The plugins offered are provided free of charge by Wirecard AG and are explicitly not part
 * of the Wirecard AG range of products and services.
 *
 * They have been tested and approved for full functionality in the standard configuration
 * (status on delivery) of the corresponding shop system. They are under General Public
 * License Version 3 (GPLv3) and can be used, developed and passed on to third parties under
 * the same terms.
 *
 * However, Wirecard AG does not provide any guarantee or accept any liability for any errors
 * occurring when used in an enhanced, customized shop system configuration.
 *
 * Operation in an enhanced, customized configuration is at your own risk and requires a
 * comprehensive test phase by the user of the plugin.
 *
 * Customers use the plugins at their own risk. Wirecard AG does not guarantee their full
 * functionality neither does Wirecard AG assume liability for any disadvantages related to
 * the use of the plugins. Additionally, Wirecard AG does not guarantee the full functionality
 * for customized shop systems or installed plugins of other vendors of plugins within the same
 * shop system.
 *
 * Customers are responsible for testing the plugin's functionality before starting productive
 * operation.
 *
 * By installing the plugin into the shop system the customer agrees to these terms of use.
 * Please do not use the plugin if you do not agree to these terms of use!
 */

/**
 * @var $block \Wirecard\ElasticEngine\Block\Widget\TestCredentialsButton
 */

echo $block->getButtonHtml();
?>
<script type="application/javascript">
    require([
        'jquery'
    ], function($){
        $('#button_test_credentials').click(function() {
            clearMessage();

            new Ajax.Request('<?= $block->getAjaxUrl() ?>', {
                parameters:   {
                    baseUrl: $('#wirecard_elasticengine_credentials_base_url').val(),
                    httpUser: $('#wirecard_elasticengine_credentials_http_user').val(),
                    httpPass: $('#wirecard_elasticengine_credentials_http_pass').val()
                },
                loaderArea:   false,
                asynchronous: true,
                onSuccess: onSuccessHandler
            });
        });

        function onSuccessHandler(response) {
            if (response.responseJSON.valid) {
                setMessage('success', response.responseJSON.message);
            } else {
                setMessage('error', response.responseJSON.message);
            }
        }

        function clearMessage() {
            $('#messages').remove();
        }

        function setMessage(type, message){
            clearMessage();
            $('.page-main-actions').after('<div id="messages"><div class="messages"><div class="message message-' + type + ' ' + type + '"><div data-ui-id="messages-message-' + type + '">' + message + '</div></div></div></div>');
        }
    });
</script>
