<?php
/**
 * Shop System Plugins:
 * - Terms of Use can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/_TERMS_OF_USE
 * - License can be found under:
 * https://github.com/wirecard/magento2-ee/blob/master/LICENSE
 */
?>
<?php foreach ($this->getMethods() as $code => $_m): ?>
<?php
    if(array_key_exists('label', $_m) && array_key_exists('value', $_m)) {
        printf("%s:%s\n", $_m['label'], $_m['value']);
    }
    if (count($_m['config']))
        print "\n";

    foreach ($_m['config'] as $key => $val)
        printf("%s:%s\n", $key, $val);
    print "\n";
?>
<?php endforeach; ?>